version: "3.9"

#containers that we have
services: 
  backend:
    build: ./backend
    ports:
    - 80:5000
    volumes:
    - ./backend:/app
    environment: 
      FLASK_ENV: development

  frontend:
    build: ./frontend/front_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/front_app:/user/src/app

    depends_on:
      - backend
