# version: "3.8"

services:
  backend:
    restart: "no"
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment: 
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: mydatabase
    depends_on:
      - mysql
      

  frontend:
    build: 
      context: ./frontend/front_app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/front_app:/user/src/app

    depends_on:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
