#containers that we have
services: 
  backend:
    build: ./backend
    ports:
    - 5000:5000
    volumes:
    - ./backend:/app
    environment: 
      FLASK_ENV: development

  frontend:
    build: 
      context: ./frontend/front_app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/front_app:/src/app
    depends_on:
      - backend
